esphome:
  name: flow3r
  platform: ESP32
  board: esp32s3box

#externa_components:
#  - source: github://pr#3625
#    components: [ gc9a01 ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: 10.42.0.1
  discovery: False

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret flow3r_api 

ota:
  password: !secret flow3r_ota

i2c:
  sda: GPIO2
  scl: GPIO1
  scan: true
  id: i2c_bus

#display:
#  - platform: gc9a01
#    reset_pin:
#      max7321: max7321_1
#      number: 2
#      mode:
#        output: true
#    cs_pin: GPIO15
#    dc_pin: GPIO33
#    rotation: 180
#    lambda: |-
#        it.line(0, 0, 100, 50);


max7321:
# bottom in schematics
  - id: max7321_1
    address: 0x6D
    i2c_id: i2c_bus
# top in schematics
  - id: max7321_2
    address: 0x6E
    i2c_id: i2c_bus

power_supply:
  - id: led_power_en
    pin:
      max7321: max7321_1
      number: 1
      mode:
        output: true

#switch:
#  - platform: gpio
#    id: lcd_rst 
#    pin:
#      max7321: max7321_1
#      number: 3
#      mode:
#        output: true

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "SW1"
  - platform: gpio
    pin: GPIO3
    name: "SW2"
  - platform: gpio
    id: "max1_pin1"
    name: "SW1_R"
    pin:
      max7321: max7321_1
      number: 0
      mode:
        input: true
  - platform: gpio
    id: "max1_pin8"
    name: "SW1_L"
    pin:
      max7321: max7321_1
      number: 7
      mode:
        input: true
  - platform: gpio
    id: "max1_pin5"
    name: "SW2_L"
    pin:
      max7321: max7321_1
      number: 4
      mode:
        input: true
  - platform: gpio
    id: "max1_pin6"
    name: "SW2_R"
    pin:
      max7321: max7321_1
      number: 5
      mode:
        input: true

  - platform: gpio
    id: "max1_pin3"
    name: "Charging"
    device_class: "BATTERY_CHARGING"
    pin:
      max7321: max7321_1
      number: 2
      inverted: true
      mode:
        input: true
  - platform: gpio
    id: "max1_pin7"
    name: "Microphone"
    device_class: "CONNECTIVITY"
    pin:
      max7321: max7321_1
      number: 6
      inverted: true
      mode:
        input: true

#  - platform: gpio
#    id: "max2_pin1"
#    name: "max2_pin1"
#    pin:
#      max7321: max7321_2
#      number: 1
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin2"
#    name: "max2_pin2"
#    pin:
#      max7321: max7321_2
#      number: 2
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin3"
#    name: "max2_pin3"
#    pin:
#      max7321: max7321_2
#      number: 3
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin4"
#    name: "max2_pin4"
#    pin:
#      max7321: max7321_2
#      number: 4
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin5"
#    name: "max2_pin5"
#    pin:
#      max7321: max7321_2
#      number: 5
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin6"
#    name: "max2_pin6"
#    pin:
#      max7321: max7321_2
#      number: 6
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin7"
#    name: "max2_pin7"
#    pin:
#      max7321: max7321_2
#      number: 7
#      mode:
#        input: true
#  - platform: gpio
#    id: "max2_pin8"
#    name: "max2_pin8"
#    pin:
#      max7321: max7321_2
#      number: 8
#      mode:
#        input: true

i2s_audio:
  i2s_lrclk_pin: GPIO11
  i2s_bclk_pin: GPIO10
  i2s_mclk_pin: GPIO18

# somehow broken, player times out
media_player:
  - platform: i2s_audio
    name: I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO13

# untested
microphone:
  - platform: i2s_audio
    id: i2s_microphone
    adc_type: external
    i2s_din_pin: GPIO12
    pdm: False

sensor:
  - platform: adc
    pin: GPIO9
    id: bat_sense
    name: Battery
    update_interval: 1s
    attenuation: 11dB
    filters:
      - multiply: 2.0
# cannot connect via i2c, according to schematics it is connected to bmi270 which is not supported by esphome yet
#  - platform: bmp581
#    address: 0x68
#    temperature:
#      name: "Flow3r Temperature"
#    pressure:
#      name: "Flow3r Pressure"

# works!
light:
  - platform: esp32_rmt_led_strip 
    rgb_order: GRB
    pin: GPIO14
    num_leds: 40
    rmt_channel: 0
    chipset: ws2812
    name: "flow3r"
    id: "flower"
    power_supply: led_power_en
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
